# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: TONVERSE
# Description of the Site
description: Craft the future
# URL of Image of the Site
site-image: /tungedng2710.github.io/assets/images/futureisland.png
# Keywords of the Site
site-keywords: AI, Mathematics
# URL for the Image of custom Favicon
favicon-url: https://avatars.githubusercontent.com/u/48611435?v=4

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/tungedng2710/tungedng2710.github.io/refs/heads/main/assets/images/heroimage.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: tungnguyen99.tn@gmail.com
facebook_username:
twitter_username:
instagram_username:
linkedin_username: tungedng2710
github_username: tungedng2710
youtube_channel_id: UCfdJlJUx5UKzM9EYqh9faxQ
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: disqus_7FVBbmOIVx

# Name of the Author
author-name: Tung Nguyen
# URL for the Image of the Author
author-image: https://github.com/tungedng2710/tungedng2710.github.io/blob/main/assets/images/shanghai1.JPG?raw=true
# 60 Words About the Author
author-about: AI tinkerer, camera nerd, and serial side-project starter. I write bite-sized guides on GenAI and computer vision so curious builders can skip the jargon and start creating.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/tungedng2710

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
